# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f7ed4c9c85b695e125c0ba7b668d38b958d20cd88bbd0e727f0c98f9acd8503c03fda0f462e47497c39ae91db7ab18c6e0651991a32e9120d9c70540d5ebc74

test:
  secret_key_base: e0249c58c74751f7ac711ac8f5bd1c8d1df5bd0a83b18ea1173699fc3d217d87610b42be6ca792c09763abb809b0c4ff30406fa3d06e38a9e31c89a7207a8b29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
