# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 011a665775eea99e23fb6d12fa57b44931b89867450a46ae902fb38532173ff0802ae6da745d5c87acaf0aceffcd2f5e1c41a8aef4f24167fc941fc6e4c2ecbe

test:
  secret_key_base: acae7f474234ba6d6bb3dc960d7be4cb441bbe7bce116192d684015fe8cfdd127c5de06bc224ac65a8be5ac02090abe7efc572f903f9cf0a31eb6ec641c4b610

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
