# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d96dc87503f784a280b8945e44bfb10d2b510f0774d6e9dd3c36301a8305834ed7b793ac80d7392ae6bafbcb69e1ada1581733fcdeaa019d51bfded81f16ab56

test:
  secret_key_base: 60ef3338509cc922a1d8cb9d04646ff4c74a77b3bacc20c23625495eb29e622987bc779df442d6fdfa0d7da21ea56d2f447cf0a878b2f2bcaed831a5378beb2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
