# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fcb5f880ff51e2ce72a8f821066c64e37a9f2dd4fcd497e415c7810dda14e54c08aeb8cb0d4fa67f93d45b2c1d0c289c91d1f1849168a3ac2d71c0d4f213480

test:
  secret_key_base: 44ddccf388a2db356ae3c7e1b41dd80df87dfd44648a537ff9ac6b52f043815c7b99dd9b013c3d116ef020f0e77540d7fdba0306e6d148b460145c37d50f2214

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
