# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad4ec26e0d3075d4c4dc0ef0caf441d636c8f57bd28eed6effa14c1b2b3398c0cfd001c6cd776bf387da01431e06e30c55644732a17369b0d4fcecb5d978ef20

test:
  secret_key_base: 97afab1697e5082fdd05a31070d7d2aff494afcf8cb4b8500f1b5ab5d7d4bb40aace9075f8f153b4e1eb33359c5d18d7b49c358ab4c49e384e9050ec1b0e0dbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
